import { ClientLayoutWrapper } from '@/shared/ui/layout/client-layout-wrapper';
import type { Metadata } from 'next';
import './styles/globals.css';

export const metadata: Metadata = {
  title: 'Japan Ranranru Racing Association',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="antialiased">
        <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
      </body>
    </html>
  );
}
